### PR TITLE
Adding text attributes as fontsize and padding

### PR DESCRIPTION
**Pull request by kevindekemele**
Textsize can be changed, as can fontpadding and padding of the button.
I think the style of the app imposes a minimum height and width, such that if you do not modify layout_height there is a certain lower limit of height.

Any suggestions are welcome

### CODE REVIEW

**Comment by jlhonora** [comment]
Hi Kevin, thanks for your contribution and sorry for the delay on getting this reviewed.

Before merging this, I'd like to see if there's a way of specifying these attributes with Android's "native" properties, as in `android:padding` and `android:textSize`. I'll get back to you whenever I have something to show.

Thanks again.

**Comment by kevindekemele** [comment]
Hello Jose,

This means adding the attributes to the android mainspace. Ill look if this is possible!

Kevin

**Comment by jlhonora** [comment]
I'm not familiar with the "mainspace" term, care to elaborate? Anyhow, here's whats on my mind:

Specify these attributes as you would with any other android component:

```
<org.honorato.multistatetogglebutton.MultiStateToggleButton
        android:id="@+id/mstb_multi2_id"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="10dip"
        android:padding="5dip"
        android:textSize="18sp"
        mstb:values="@array/dogs_array" />
```

Then, retrieve those in code and apply to each component as needed.

`textSize` should be straightforward. `padding` is a bit trickier: what would you expect with `paddingLeft` for example? Pad each single button or only pad the left side of the entire component?

**Comment by kevindekemele** [comment]
In the meantime I have found how to use the "android" namespace (not mainspace, typing error!).
For the padding, maybe the normal "android" padding should be affect the multistatebutton as a whole, and a custom padding, with the "mstb" namespace, to specify that padding affects each button separately.

**Comment by jlhonora** [comment]
Great! Thanks for the clarification.

I don't think the individual padding should be necessary, what's the use case that you have in mind?

**Comment by kevindekemele** [comment]
This commit: Padding is functional
-android:padding adds padding to the LinearLayout in which the buttons recide. This seems the most logical way of padding
-mstb:mstbButtonPadding adds padding to the buttons itself (that is the padding adding of the text in the button)

Previous commits
android:textFontPadding
android:Textsize

Do as you expect

You can merge, or suggest more changes

**Comment by jlhonora** [comment]
Hi Kevin,

Sorry for taking so long. I really appreciate the effort but I'm closing this for now. I'm saying the following with the best of intentions, please excuse me if they sound a bit harsh:

- I'm not sure padding is a pressing need right now. Material design has rigorous standards about paddings and layouts in general, so using custom paddings in buttons is a way of diverting from that. This is the main reason for not merging.
- I think there are far too many new global variables in `MultiStateToggleButton`
- The `setButtonPadding*` are basically the same methods with few differences
- In general there are many structure improvements that could be made

**Pull request closed without merging**
